In [1]:
import torch

points = torch.zeros(6)
print(points)

tensor([0., 0., 0., 0., 0., 0.])


In [2]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

float(points[0]),float(points[1])

(4.0, 1.0)

In [3]:
#use of 2D tensor

pointsNew = torch.tensor([[4.1,1.1],[5.1,3.1],[2.1,1.1]])
pointsNew

tensor([[4.1000, 1.1000],
        [5.1000, 3.1000],
        [2.1000, 1.1000]])

In [4]:
pointsNew.shape

torch.Size([3, 2])

In [5]:
pointsNew[0,1]

tensor(1.1000)

In [6]:
pointsNew[0]

tensor([4.1000, 1.1000])

In [7]:
double_points = torch.ones(10,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[22,33]],dtype=torch.short)

print(double_points)
print(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[ 1,  2],
        [22, 33]], dtype=torch.int16)


In [8]:
some_list = list(range(6))


In [9]:
pointsNew[1:]

tensor([[5.1000, 3.1000],
        [2.1000, 1.1000]])

In [10]:
pointsNew[1:,:]

tensor([[5.1000, 3.1000],
        [2.1000, 1.1000]])

In [11]:
a = torch.ones(3,2)
a_transpose = torch.transpose(a,0,1)

print(a.shape)
print(a_transpose.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [12]:
x = torch.ones(2,3)
y = torch.rand(2,3)

z1 = x + y
z2 = torch.add(x,y)

print(z1)
print(z2)

tensor([[1.5685, 1.0939, 1.8268],
        [1.4773, 1.4094, 1.2003]])
tensor([[1.5685, 1.0939, 1.8268],
        [1.4773, 1.4094, 1.2003]])


In [13]:
new = torch.ones(3,2)
new.zero_() #zeroes out all the elements of the tensor
print(new)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [16]:
import numpy

In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)  #numpy array too changed in value!

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
